export default {
  SETUP_USER_BEGIN: 'SETUP_USER_BEGIN',
  SETUP_USER_SUCCESS: 'SETUP_USER_SUCCESS',
  SETUP_USER_FAILED: 'SETUP_USER_FAILED',

  DISPLAY_ALERT: 'SHOW_ALERT',
  CLEAR_ALERT: 'CLEAR_ALERT',
  LOGOUT_USER: 'LOGOUT_USER',

  GET_SHOPS_BEGIN: 'GET_SHOPS_BEGIN',
  GET_SHOPS_SUCCESS: 'GET_SHOPS_SUCCESS',
  GET_SHOPS_FAILED: 'GET_SHOPS_FAILED',

  GET_SHOP_GOODS_BEGIN: 'GET_SHOP_GOODS_BEGIN',
  GET_SHOP_GOODS_SUCCESS: 'GET_SHOP_GOODS_SUCCESS',
  GET_SHOP_GOODS_FAILED: 'GET_SHOP_GOODS_FAILED',

  SET_CURRENT_SHOP: 'SET_CURRENT_SHOP',

  ADD_ITEM: 'ADD_ITEM',
  CLEAR_CART: 'CLEAR_CART',
  REMOVE_ITEM: 'REMOVE_ITEM',
  TOGGLE_AMOUNT: 'TOGGLE_AMOUNT',
  GET_TOTALS: 'GET_TOTALS',
  SET_CART: 'SET_CART',

  ORDER_BEGIN: 'ORDER_BEGIN',
  ORDER_SUCCESS: 'ORDER_SUCCESS',
  ORDER_FAILED: 'ORDER_FAILED',

  GET_ORDER_HISTORY_BEGIN: 'GET_ORDER_HISTORY_BEGIN',
  GET_ORDER_HISTORY_SUCCESS: 'GET_ORDER_HISTORY_SUCCESS',
  GET_ORDER_HISTORY_FAILED: 'GET_ORDER_HISTORY_FAILED',

  SET_ORDER_USER: 'SET_ORDER_USER',
}
